### ISSUE TITLE
Not compiling with newest Arduino IDE

### ISSUE THREAD

**Issue by Eisbaeeer** [plainFlight/plainFlightController#4]
Hi
I tried to compile fresh installation of Arduino (as in manual).

Arduino 2.3.2
MPU6050 1.3.1
esp32 Espressif Systems 3.0.4

Throwing this error:
![image](https://github.com/user-attachments/assets/8f61bcaa-9802-4be0-b1b0-8f8b91542bbf)

Is it possible to move the source to platformio?
This will be more stable regarding updates of lib´s.

Greets Lars

**Comment by plainFlight** [comment]
Manual shows 2.0.14 for Espressif Systems library. It will compile with that version.

**Comment by Eisbaeeer** [comment]
The sketch is compiling with 2.0.14
Thanks a lot!
